api_version: 1
runtime: python27
threadsafe: true
service: uploader

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /static/
  static_dir: static/
- url: .*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- ^.*.example
- bower_components
- env
- frontend
- htmlcov
- lib/Crypto
- lib/PIL
- node_modules
- testing
